### PR TITLE
[#186] build Heroku review apps using updated app.json

### PR DESCRIPTION
**Pull request by tiredpixel**
The previous `app.json` is out-of-date and doesn't work, since it was designed for register-v1. Rewrite file based on register-v2-stg, using the Heroku app-json template.

https://dashboard.heroku.com/apps/openownership-register-v2-stag/app-json

### CODE REVIEW

**Comment by tiredpixel** [comment]
References https://github.com/openownership/register/issues/186 .

**Comment by tiredpixel** [comment]
The review app deployment in https://github.com/openownership/register/pull/197 shows that this works. I'm not sure why some PRs get added to the project board, anyway.

**Comment by StephenAbbott** [comment]
@tiredpixel Whoops. I think I manually tagged this PR to the OO Register project. Will not do that in future

**Comment by tiredpixel** [comment]
Thanks, @StephenAbbott . I think it's probably fine to manually tag a PR to the project if there's no referenced ticket—for example if someone submitted a PR without some linked ticket for the work—but if there's already a ticket a PR references, tagging them manually leads to there being multiple items on the project board related to the same thing. That's not a problem, per se—but they get out of sync with the statuses since they're not automatically updated when the underlying issue moves into _testing_ or _done_. If that makes sense. :)

**Pull request merged**
